apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mailhog
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailhog
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/seleorplatform_saleor-backend-tier: "true"
        io.kompose.service: mailhog
    spec:
      containers:
      - image: mailhog/mailhog
        imagePullPolicy: ""
        name: mailhog
        ports:
        - containerPort: 1025
        - containerPort: 8025
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
